### ISSUE TITLE
Apollo CentOS8 migration checklist

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#148]
To do on dev:
- [x] @g8tor: cron jobs - migrated over
- [x] @mpoelchau : https://github.com/NAL-i5K/general_issues/issues/127
  - need to make sure that permissions are fixed
- [x] Acunetix scan
- [x] 508 waiver is documented in ISD ticket #37490 - need to re-confirm
- [x] change gene page linkout URLs in Tripal from space to underscore between genus and species (need to figure out who should do this and when)
- [x] @mpoelchau triple-check that all the places that need to switch from space to underscore are updated

To do on Stage:
- [ ] barman setup (ISD)
-  [x] BigIP configuration and setup (ISD)
- [x] @g8tor  test content migration from prod and figure out how long it takes
- [x] @mpoelchau test functionality
- [x] @g8tor change spaces to underscores in genomics-workspace jbrowse URLs on i5k-stage-node1
- [x] @g8tor pull tripal branch https://github.com/isdapps/i5k-tripal/tree/genepage-iframe-fix onto i5k-stage-node1, and modify apollo server to apollo2-stage in web sites/all/modules/custom/web_apollo/web_apollo.admin.inc 
- [x] @g8tor check on gff3 download issue - I suspect nginx is not allowing  https://apollo2-dev.nal.usda.gov/bacole/IOService?
- [x] @g8tor make directories group writable: /app/data/BCM_i5k_pilot, /app/data/other_species, /app/data/modencodeoperation=write&adapter=GFF3&options=output%3Dfile%26format%3Dgzip&tracks=all_tracks
- [ ] @mpoelchau rebuild war for apollo1 agrpla with correct blat db...

To do on deployment day:
- [x] disable live site - stop tomcat
- CONTENT MIGRATION. @g8tor do content migration from apollo-node1 to apollo2-stage-node1 after disabling live site
  - dump content from postgres databases
  - rsync /app/data/other_species, /app/data/BCM_i5k_pilot, /app/data/modencode from apollo-node1 to apollo2-stage-node1 (is it possible to do exclude the tracklist.json files during this?) 
- CONTENT UPDATES 
  - [x] @g8tor make directories group writable: /app/data/BCM_i5k_pilot, /app/data/other_species, /app/data/modencode
  - [x] @mpoelchau run script from https://github.com/NAL-i5K/general_issues/issues/127 on migrated content
  - [x] @g8tor change spaces to underscores in genomics-workspace jbrowse URLs on i5k-node1 (https://github.com/NAL-i5K/general_issues/issues/121)
  - [x] @g8tor the apollo2 database needs the common_name field so that %20 is replaced with _ in the "organism" table. (https://github.com/NAL-i5K/general_issues/issues/121)
  - [x] @g8tor pull tripal branch https://github.com/isdapps/i5k-tripal/tree/genepage-iframe-fix onto i5k-node1, and modify sites/all/modules/custom/web_apollo/web_apollo.admin.inc - l. 326 needs to change to apollo-node1, and l. 667 and 668 need to change to apollo (https://github.com/NAL-i5K/general_issues/issues/121)
; do drush cc all
- [x] clone stage to prod (ISD)
- [x] BigIP configuration and setup (ISD)
- [x] @g8tor change conf files
- [x] @mpoelchau test functionality
- [x] @mpoelchau merge tripal genepage-iframe-fix branch into master
- [x] @mpoelchau @g8tor @childers work with ISD on backup and disabling of prod, stage, dev

**Comment by mpoelchau** [comment]
CentOS8 migration finished some time ago.
