### ISSUE TITLE
Genome assembly update: Drosophila eugracilis

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#171]
This is a fairly straightforward genome assembly update. 
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_018153835.1
- publication associated with assembly: https://doi.org/10.7554/eLife.66405

- [x] Shelly: Run the final_workflow.cwl component of the organism_onboarding pipeline. THIS WILL NEED THE 'NO GAP' VERSION OF THE CONTAINER. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding 
- [x] Shelly: Add gene page linkouts from Apollo. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#2-add-gene-page-linkouts-from-apollo
- [x] Shelly: Run RNA-Seq pipeline. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline 
- [x] Monica - run gene processing pipeline on Ceres for gene pages
- [ ] 
Rest: Monica and Surya will divide up. 
- [x] @suryasaha  3. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1
- [x] @suryasaha 4. Apollo setup on the apollo2-stage-node1 server. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-server
- @mpoelchau 4b. deprecate existing Apollo instance
  - [x]  on apollo-stage
  - [x] apollo-prod
- [x] @suryasaha 5. Set up Tripal ANALYSIS pages. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages AND 
- [x] @mpoelchau 5b. Update organism page and handle old analysis pages https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates
  - [x]  Organism page (https://i5k-stage-node1.nal.usda.gov/bio_data/836502): remove publication, change description to wikipedia description. Need to work on obsolete field to display (this will have to happen in the future). 
  - No changes to old analysis pages. 
- [x] @mpoelchau 6. Set up gene pages.
- [x] @suryasaha 7. Set up BLAST and HMMER (genomics-workspace). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace
- [ ] @mpoelchau 7b. deprecate old genomics-workspace files and entries.
- [x] @suryasaha 8. Set up data downloads. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads
- [x] @suryasaha 9. Functional annotation
- [x] @suryasaha @mpoelchau 10. Final Test List. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list
- [x] @mpoelchau 11. Advertising

**Comment by suryasaha** [comment]
Move fasta files
```
[surya.saha@i5k-stage-node1 ~]$ cp /app/data/other_species/droeug/ASM1815383v1/scaffold/GCF_018153835.1_ASM1815383v1_genomic.fna /usr/local/i5k/media/blast/db/

[surya.saha@i5k-stage-node1 ~]$ cp /app/data/other_species/droeug/ASM1815383v1/scaffold/analyses/Drosophila_eugracilis_Annotation_Release_102/GCF_018153835.1_ASM1815383v1_rna_from_genomic.fna /usr/local/i5k/media/blast/db/
[surya.saha@i5k-stage-node1 ~]$ cp /app/data/other_species/droeug/ASM1815383v1/scaffold/analyses/Drosophila_eugracilis_Annotation_Release_102/GCF_018153835.1_ASM1815383v1_cds_from_genomic.fna /usr/local/i5k/media/blast/db/
[surya.saha@i5k-stage-node1 ~]$ cp /app/data/other_species/droeug/ASM1815383v1/scaffold/analyses/Drosophila_eugracilis_Annotation_Release_102/GCF_018153835.1_ASM1815383v1_translated_cds.faa /usr/local/i5k/media/blast/db/
```

Add organism and fasta files
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addorganism Drosophila eugracilis
Succeessfully add to database
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Drosophila eugracilis -t nucleotide Genome Assembly -f /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_genomic.fna -d 'Drosophila eugracilis genome assembly, ASM1815383v1'
you can move to makeblastdb and populate sequence step
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Drosophila eugracilis -t nucleotide Transcript -f /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_rna_from_genomic.fna -d 'Drosophila eugracilis NCBI Annotation Release 102, transcripts'
you can move to makeblastdb and populate sequence step
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Drosophila eugracilis -t peptide Protein -f /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_translated_cds.faa -d 'Drosophila eugracilis NCBI Annotation Release 102, translated CDS'
you can move to makeblastdb and populate sequence step
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Drosophila eugracilis -t nucleotide Transcript -f /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_cds_from_genomic.fna -d 'Drosophila eugracilis NCBI Annotation Release 102, CDS'
you can move to makeblastdb and populate sequence step
```

Make blast DBs and populate
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_genomic.fna -m
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_genomic.fna -p
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_rna_from_genomic.fna -m
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_rna_from_genomic.fna -p
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_translated_cds.faa -m
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_translated_cds.faa -p
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_cds_from_genomic.fna -m
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_utility /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_cds_from_genomic.fna -p
1 species finished
all done
```

Make visible
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_shown /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_genomic.fna --shown true
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_shown /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_rna_from_genomic.fna --shown true
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_shown /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_translated_cds.faa --shown true
1 species finished
all done
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py blast_shown /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_cds_from_genomic.fna --shown true
1 species finished
all done
```

Add genome assembly fasta file to jbrowse
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addjbrowse /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_genomic.fna https://apollo.nal.usda.gov/apollo/Drosophila_eugracilis/jbrowse/
JBrowseSetting Successfully Created.
```


Set up hmmer for peptide fasta file
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addhmmer Drosophila eugracilis -f /usr/local/i5k/media/blast/db/GCF_018153835.1_ASM1815383v1_translated_cds.faa -d "Drosophila eugracilis NCBI Annotation release 102, translated CDS"
Success
```

**Comment by suryasaha** [comment]
Looks fine on prod but blast results track timing out 
![image](https://user-images.githubusercontent.com/1084749/135645964-400ca1d3-7d38-4232-855b-bda7e7bf120d.png)

**Comment by mpoelchau** [comment]
The problem is that the title in the blast_blastdb has the full URL. I think this is because you used the full path of the fasta file in the python manage.py addblast command - it should only be the name. I have fixed the database entries on stage and prod, which included all new entries for droele, droeug, drokik, vencan, rhimic, and ladful. @suryasaha can you confirm that they work now?

**Comment by suryasaha** [comment]
Linkouts to jbrowse with blast results work fine now. Thanks! @mpoelchau
