### ISSUE TITLE
Genome assembly update: Copidosoma floridanum

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#173]
This is a fairly straightforward genome assembly update. @mpoelchau needs to get in touch with the genome coordinator before the move. 
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_000648655.2
- publication associated with assembly: https://doi.org/10.1186/s13059-019-1925-7

- [ ] Shelly: Run the final_workflow.cwl component of the organism_onboarding pipeline. This will need the regular version of the container (pipeline.sif). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding 
- [ ] Shelly: Add gene page linkouts from Apollo. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#2-add-gene-page-linkouts-from-apollo
- [ ] Shelly: Run RNA-Seq pipeline. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline 

Rest: Monica and Surya will divide up. 
- [ ] @suryasaha  3. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1
- [ ] @suryasaha 4. Apollo setup on the apollo2-stage-node1 server. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-server
- @mpoelchau 4b. deprecate existing Apollo instance
  - [ ]  on apollo-stage
  - [ ] apollo-prod
- [ ] @suryasaha 5. Set up Tripal ANALYSIS pages. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages AND 
- [ ] @mpoelchau 5b. Update organism page and handle old analysis pages https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates
- [ ] @mpoelchau 6. Set up gene pages.
- [ ] @suryasaha 7. Set up BLAST and HMMER (genomics-workspace). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace
- [ ] @mpoelchau 7b. deprecate old genomics-workspace files and entries.
- [ ] @suryasaha 8. Set up data downloads. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads
- [ ] @suryasaha 9. Functional annotation
- [ ] @suryasaha @mpoelchau 10. Final Test List. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list
- [ ] @mpoelchau 11. Advertising
