### ISSUE TITLE
Genome assembly update: Drosophila ficusphila

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#179]
This is a fairly straightforward genome assembly update. 
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_018152265.1
- publication associated with assembly: https://doi.org/10.7554/eLife.66405

- [x] Debbie: Run the final_workflow.cwl component of the organism_onboarding pipeline. THIS WILL NEED THE 'NO GAP' VERSION OF THE CONTAINER - `/project/nal_genomics/shared_programs/pipeline-OrgOn-nogaps-branch.sif`. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding 
- [x] Debbie: Add gene page linkouts from Apollo. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#2-add-gene-page-linkouts-from-apollo
- [x] Debbie: Run RNA-Seq pipeline. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline 
- [x] Monica - run gene processing pipeline on Ceres for gene pages

- [x] @ mpoelchau  3. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1
- [x] @ mpoelchau 4. Apollo setup on the apollo2-stage-node1 server. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-server
- @mpoelchau 4b. deprecate existing Apollo instance
  - [x]  on apollo-stage
  - [x] apollo-prod
- [x]  5. Set up Tripal ANALYSIS pages. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages AND 
- [x]  5b. Update organism page and handle old analysis pages https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates
  - [x] Organism page (https://i5k-stage-node1.nal.usda.gov/bio_data/836502): remove publication, change description to wikipedia description
  - No changes to old analysis pages.   
- [x] @mpoelchau 6. Set up gene pages.
- [x] 7. Set up BLAST and HMMER (genomics-workspace). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace
- [x] @mpoelchau 7b. deprecate old genomics-workspace files and entries.
- [x] @ mpoelchau 8. Set up data downloads. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads
- [x] @suryasaha 9. Functional annotation
- [x] @ mpoelchau @mpoelchau 10. Final Test List. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list
- [ ] @mpoelchau 11. Advertising

**Comment by mpoelchau** [comment]
```sudo su -l i5k
cp /app/data/other_species/drofic/ASM1815226v1/scaffold/GCF_018152265.1_ASM1815226v1_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/drofic/ASM1815226v1/scaffold/analyses/Drosophila_ficusphila_Annotation_Release_102/GCF_018152265.1_ASM1815226v1_cds_from_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/drofic/ASM1815226v1/scaffold/analyses/Drosophila_ficusphila_Annotation_Release_102/GCF_018152265.1_ASM1815226v1_rna_from_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/drofic/ASM1815226v1/scaffold/analyses/Drosophila_ficusphila_Annotation_Release_102/GCF_018152265.1_ASM1815226v1_translated_cds.faa /usr/local/i5k/media/blast/db/

#python manage.py addorganism Drosophila ficusphila

python manage.py addblast Drosophila ficusphila -t nucleotide Genome Assembly -f GCF_018152265.1_ASM1815226v1_genomic.fna -d 'Drosophila ficusphila genome assembly, ASM1815226v1'
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_genomic.fna -m
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_genomic.fna -p
python manage.py blast_shown GCF_018152265.1_ASM1815226v1_genomic.fna --shown true
#modified blast jbrowse setting in database

python manage.py addblast Drosophila ficusphila -t nucleotide Transcript -f GCF_018152265.1_ASM1815226v1_rna_from_genomic.fna -d 'Drosophila ficusphila NCBI Annotation release 102, transcripts'
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_rna_from_genomic.fna -m
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_rna_from_genomic.fna -p
python manage.py blast_shown GCF_018152265.1_ASM1815226v1_rna_from_genomic.fna --shown true

python manage.py addblast Drosophila ficusphila -t peptide Protein -f GCF_018152265.1_ASM1815226v1_translated_cds.faa -d 'Drosophila ficusphila NCBI Annotation release 102, translated CDS'
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_translated_cds.faa -m
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_translated_cds.faa -p
python manage.py blast_shown GCF_018152265.1_ASM1815226v1_translated_cds.faa --shown true

python manage.py addblast Drosophila ficusphila -t nucleotide Transcript -f GCF_018152265.1_ASM1815226v1_cds_from_genomic.fna -d Drosophila ficusphila NCBI Annotation release 102, CDS
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_cds_from_genomic.fna -m
python manage.py blast_utility GCF_018152265.1_ASM1815226v1_cds_from_genomic.fna -p
python manage.py blast_shown GCF_018152265.1_ASM1815226v1_cds_from_genomic.fna --shown true

python manage.py addhmmer Drosophila ficusphila -f /usr/local/i5k/media/blast/db/GCF_018152265.1_ASM1815226v1_translated_cds.faa -d 'Drosophila ficusphila NCBI Annotation release 102, translated CDS'
#deprecated other files in database
```
