### ISSUE TITLE
New organism: Tribolium madens

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#180]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_015345945.1
- publication associated with assembly: none

- [x] Debbie. 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] Debbie. 2. Add gene page linkouts from Apollo (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#2-add-gene-page-linkouts-from-apollo)
- [x] Debbie. 3. Run RNA-Seq pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)
- [x] 4. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 5. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 6. Set up Tripal pages (except gene pages) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 6b. Set up Tripal gene pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/adding-features-to-tripal-for-gene-pages) 
- [x] 7. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 8. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 9. Functional annotation
- [x] 10. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [x] 11. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising)

**Comment by mpoelchau** [comment]
Functional annotation protein set: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/015/345/945/GCF_015345945.1_Tmad_KSU_1.1/GCF_015345945.1_Tmad_KSU_1.1_protein.faa.gz

**Comment by amcooksey** [comment]
Functional Annotation data at CyVerse Data Store:
https://data.cyverse.org/dav-anon/iplant/home/amcooksey/i5k/annotation_outputs/Tribolium_madens/Tribolium_madens_annotations.tgz

**Comment by amcooksey** [comment]
Reformatted annotation files with README file:
CERES: /project/nal_genomics/amanda.cooksey/protein_sets/cyverse_data/Tribolium_madens

**Comment by amcooksey** [comment]
Moved this data to match file paths for other species:
CERES: /project/nal_genomics/amanda.cooksey/protein_sets/Tribolium_madens
