### ISSUE TITLE
Genome assembly update: Drosophila takahashii

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#184]
This is a fairly straightforward genome assembly update. 
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_018152695.1
- publication associated with assembly: https://doi.org/10.7554/eLife.66405

- [x] Tina: Run the final_workflow.cwl component of the organism_onboarding pipeline. THIS WILL NEED THE 'NO GAP' VERSION OF THE CONTAINER - `/project/nal_genomics/shared_programs/pipeline-OrgOn-nogaps-branch.sif`. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding 
- [x] Tina: Add gene page linkouts from Apollo. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#2-add-gene-page-linkouts-from-apollo
- [x] Tina: Run RNA-Seq pipeline. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline 
- [x] Monica - run gene processing pipeline on Ceres for gene pages

Monica and/or Chris:
- [x]  3. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1
- [x] 4. Apollo setup on the apollo2-stage-node1 server. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-server
- 4b. deprecate existing Apollo instance
  - [x] on apollo-stage
  - [ ] apollo-prod
- [x]  Monica: 5. Set up Tripal ANALYSIS pages. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages AND 
- [x]  Monica: 5b. Update organism page and handle old analysis pages https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates
  - [x] Monica: Organism page (https://i5k-stage-node1.nal.usda.gov/bio_data/836502): remove publication, change description to wikipedia description
  - No changes to old analysis pages.   
- [x]  Monica: 6. Set up gene pages.
- [x] 7. Set up BLAST and HMMER (genomics-workspace). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace
- [x] 7b. deprecate old genomics-workspace files and entries.
- [x] 8. Set up data downloads. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads
- [x] @amcooksey  9. Functional annotation
- [ ] 10. Final Test List. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list
- [ ] 11. Advertising

**Comment by amcooksey** [comment]
Functional annotation completed.
CERES: /project/nal_genomics/amanda.cooksey/protein_sets/Drosophila_takahashii
