### ISSUE TITLE
New organism: Schistocerca americana 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#186]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_021461395.2
- publication associated with assembly: none
- due date: May 2nd
- community contact: Hojun Song, Texas A&M University; Anna Childers, Agricultural Research Service; Olga Dudchenko, Baylor College of Medicine

Tina:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [ ] 3. Run RNA-Seq pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

Monica:
- [x] 4. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 5. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 6. Set up Tripal pages (except gene pages) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 7. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 8. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 9. Functional annotation
- [x] 10. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [x] 11. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising)

**Comment by mpoelchau** [comment]
@amcooksey I'm glad the functional annotation worked!

**Comment by amcooksey** [comment]
added organism page. unpublished.

**Comment by mpoelchau** [comment]
@amcooksey I had already set up Tripal pages for this one a couple of weeks ago - here's the organism page: https://i5k.nal.usda.gov/bio_data/1394307. I'm surprised Tripal let you add the same organism! I'd rather stick with the older page since it already is linked in Tripal and Chado to other analyses. Can you delete the newer page, and update the old page with the new S. americana photo?

**Comment by amcooksey** [comment]
update photo and image credit. deleted duplicate page

**Comment by mpoelchau** [comment]
Out - closing for now, will re-open once the RNA-Seq pipeline is updated.
