### ISSUE TITLE
New organism: Neodiprion pinetum

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#187]
Our first Ag100Pest genome!

See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_021155775.1
- publication associated with assembly: NA
- due date: April 5th

# Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding) (@debbiedai )
- [x] 2. Run RNA-Seq pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline) (@debbiedai )

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1) (@amcooksey)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) (@amcooksey)
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)(@amcooksey)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)(@amcooksey)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads) (@amcooksey)
- [x] 6. Functional annotation (@amcooksey)
- [x] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list) (@childers)
- [x] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
functional annotation on CERES: /project/nal_genomics/amanda.cooksey/protein_sets/Neodiprion_pinetum/NCBI Annotation Release 100 functional annotation
