### ISSUE TITLE
New organism: Neodiprion fabricii

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#189]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_021155785.1
- publication associated with assembly: NA
- due date: April 5th
- 
# Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding) (@debbiedai )
- [x] 2. Run RNA-Seq pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline) (@debbiedai )

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Functional annotation (@amcooksey)
- [x] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [x] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by debbiedai** [comment]
RNA-Seq pipeline can not be run because there is no RNA-Seq SRA available from NCBI.

**Comment by mpoelchau** [comment]
Based on an email from the community contact, we can map RNA-Seq from Neodiprion lecontei (taxid 441921) to this assembly.

**Comment by mpoelchau** [comment]
cp /app/data/other_species/neofab/iyNeoFabr1.1/scaffold/GCF_021155785.1_iyNeoFabr1.1_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/neofab/iyNeoFabr1.1/scaffold/analyses/Neodiprion_fabricii_Annotation_Release_100/GCF_021155785.1_iyNeoFabr1.1_cds_from_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/neofab/iyNeoFabr1.1/scaffold/analyses/Neodiprion_fabricii_Annotation_Release_100/GCF_015345945.1_Tmad_KSU_1.1_rna_from_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/neofab/iyNeoFabr1.1/scaffold/analyses/Neodiprion_fabricii_Annotation_Release_100/GCF_021155785.1_iyNeoFabr1.1_translated_cds.faa /usr/local/i5k/media/blast/db/


python manage.py addorganism Neodiprion fabricii

python manage.py addblast Neodiprion fabricii -t nucleotide Genome Assembly -f GCF_021155785.1_iyNeoFabr1.1_genomic.fna -d 'Neodiprion fabricii genome assembly, iyNeoFabr1.1'
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_genomic.fna -m
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_genomic.fna -p
python manage.py blast_shown GCF_021155785.1_iyNeoFabr1.1_genomic.fna --shown true
python manage.py addjbrowse GCF_021155785.1_iyNeoFabr1.1_genomic.fna https://apollo.nal.usda.gov/apollo/Neodiprion_fabricii/jbrowse/

python manage.py addblast Neodiprion fabricii -t nucleotide Transcript -f GCF_021155785.1_iyNeoFabr1.1_rna_from_genomic.fna -d 'Neodiprion fabricii NCBI Annotation release 100, transcripts'
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_rna_from_genomic.fna -m
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_rna_from_genomic.fna -p
python manage.py blast_shown GCF_021155785.1_iyNeoFabr1.1_rna_from_genomic.fna --shown true

python manage.py addblast Neodiprion fabricii -t peptide Protein -f GCF_021155785.1_iyNeoFabr1.1_translated_cds.faa -d 'Neodiprion fabricii NCBI Annotation release 100, translated CDS'
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_translated_cds.faa -m
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_translated_cds.faa -p
python manage.py blast_shown GCF_021155785.1_iyNeoFabr1.1_translated_cds.faa --shown true

python manage.py addblast Neodiprion fabricii -t nucleotide Transcript -f GCF_021155785.1_iyNeoFabr1.1_cds_from_genomic.fna -d Neodiprion fabricii NCBI Annotation release 100, CDS
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_cds_from_genomic.fna -m
python manage.py blast_utility GCF_021155785.1_iyNeoFabr1.1_cds_from_genomic.fna -p
python manage.py blast_shown GCF_021155785.1_iyNeoFabr1.1_cds_from_genomic.fna --shown true

python manage.py addhmmer Neodiprion fabricii -f /usr/local/i5k/media/blast/db/GCF_021155785.1_iyNeoFabr1.1_translated_cds.faa -d 'Neodiprion fabricii NCBI Annotation release 100, translated CDS'

**Comment by amcooksey** [comment]
functional annotation on CERES: /project/nal_genomics/amanda.cooksey/protein_sets/Neodiprion_fabricii/NCBI Annotation Release 100 functional annotation
