### ISSUE TITLE
New organism: Schistocerca piceifrons

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#191]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_021461385.2
- publication associated with assembly: 
- due date: May 2nd
- community contact: Hojun Song, Texas A&M University; Anna Childers, Agricultural Research Service; Olga Dudchenko, Baylor College of Medicine

# Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 2. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)
  -  note - big assembly, not sure if we can provide the bam file

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Functional annotation (@amcooksey)
- [x] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [x] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
CERES  file path: /project/nal_genomics/amanda.cooksey/protein_sets/Schistocerca_piceifrons/NCBI Annotation Release 100 functional annotation

**Comment by childers** [comment]
```Copy files into place
cp /app/data/other_species/schpic/iqSchPice1.1/scaffold/GCF_021461385.2_iqSchPice1.1_genomic.fna /usr/local/i5k/media/blast/db/

cp /app/data/other_species/schpic/iqSchPice1.1/scaffold/analyses/NCBI\ Schistocerca\ piceifrons\ Annotation\ Release\ 100/GCF_021461385.2_iqSchPice1.1_cds_from_genomic.fna   /usr/local/i5k/media/blast/db/

cp /app/data/other_species/schpic/iqSchPice1.1/scaffold/analyses/NCBI\ Schistocerca\ piceifrons\ Annotation\ Release\ 100/GCF_021461385.2_iqSchPice1.1_rna_from_genomic.fna   /usr/local/i5k/media/blast/db/
 cp /app/data/other_species/schpic/iqSchPice1.1/scaffold/analyses/NCBI\ Schistocerca\ piceifrons\ Annotation\ Release\ 100/GCF_021461385.2_iqSchPice1.1_translated_cds.faa /usr/local/i5k/media/blast/db/

1. Add organism: 
    1. python manage.py addorganism Schistocerca piceifrons 
2. Add each of the fasta files:
    * genome fasta: 
python manage.py addblast Schistocerca piceifrons -t nucleotide Genome Assembly -f GCF_021461385.2_iqSchPice1.1_genomic.fna -d 'Schistocerca piceifrons genome assembly, iqSchPice1.1' 
    * RNA fasta file: 
python manage.py addblast Schistocerca piceifrons -t nucleotide Transcript -f GCF_021461385.2_iqSchPice1.1_rna_from_genomic.fna -d 'Schistocerca piceifrons NCBI Annotation release 100, transcripts' 
    * Peptide fasta file: 
python manage.py addblast Schistocerca piceifrons -t peptide Protein -f GCF_021461385.2_iqSchPice1.1_translated_cds.faa -d 'Schistocerca piceifrons NCBI Annotation release 100, translated CDS' 
    * CDS fasta file: 
python manage.py addblast Schistocerca piceifrons -t nucleotide Transcript -f GCF_021461385.2_iqSchPice1.1_cds_from_genomic.fna -d Schistocerca piceifrons NCBI Annotation release 100, CDS 
1. Process each fasta file:
    * Make blast database: 

	python manage.py blast_utility GCF_021461385.2_iqSchPice1.1_genomic.fna -m 
	python manage.py blast_utility GCF_021461385.2_iqSchPice1.1_rna_from_genomic.fna -m 
	python manage.py blast_utility GCF_021461385.2_iqSchPice1.1_cds_from_genomic.fna -m 
	python manage.py blast_utility GCF_021461385.2_iqSchPice1.1_translated_cds.faa -m 

    * populate sequence table: 
		python manage.py blast_utility GCF_021461385.2_iqSchPice1.1_genomic.fna -p 
		python manage.py blast_utility GCF_021461385.2_iqSchPice1.1_rna_from_genomic.fna -p 
		python manage.py blast_utility GCF_021461385.2_iqSchPice1.1_cds_from_genomic.fna -p 
		python manage.py blast_utilityGCF_021461385.2_iqSchPice1.1_translated_cds.faa -p 

    * display in UI: 
		python manage.py blast_shown GCF_021461385.2_iqSchPice1.1_genomic.fna --shown true 
		python manage.py blast_shown GCF_021461385.2_iqSchPice1.1_rna_from_genomic.fna --shown true 
		python manage.py blast_shown GCF_021461385.2_iqSchPice1.1_cds_from_genomic.fna --shown true 
		python manage.py blast_shown GCF_021461385.2_iqSchPice1.1_translated_cds.faa --shown true 

1. For the genome assembly fasta file:
python manage.py addjbrowse GCF_021461385.2_iqSchPice1.1_genomic.fna https://apollo.nal.usda.gov/apollo/Schistocerca_piceifrons/jbrowse/


1. Set up hmmer for peptide fasta file: 
python manage.py addhmmer Schistocerca piceifrons -f /usr/local/i5k/media/blast/db/GCF_021461385.2_iqSchPice1.1_translated_cds.faa -d 'Schistocerca piceifrons NCBI Annotation release [release number], translated CDS'

```

**Comment by amcooksey** [comment]
Added organism page. Could not add photo. When I try to upload I get this error: "AJAX HTTP request terminated abnormally"
Image is only 1.8 MB.

**Comment by mpoelchau** [comment]
@amcooksey for S. gregaria I saved the file in png format and reduced the size, and was able to upload it. Could you try this for this species?

**Comment by amcooksey** [comment]
@mpoelchau That seems to have worked.
