### ISSUE TITLE
Genome assembly update: Neodiprion lecontei

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#197]
# OGS remapping - TBD, @mpoelchau 

- [ ] request whole-genome alignment
- [ ] Set up data directories and get data
- [x] run remap-gff3

# Change old content - @mpoelchau 
- [x] back up and deprecate old Apollo2
- [x] back up and deprecate old fasta files in BLAST 
- [x] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications - @amcooksey  
See https://gitlab.com/i5k_Workspace/workspace_roadmap/wikis/Adding-an-organism-to-the-i5k-Workspace-NAL-version for full description of each task. @amcooksey we'll need to coordinate on some of aspects of the server setup

- assembly accession number: [GCF_021901455.1/](https://www.ncbi.nlm.nih.gov/assembly/GCF_021901455.1/)
- publication associated with assembly: none
- due date: 7/30/2022
- community contact: Catherine Linnen, University of Kentucky
- this is an Ag100Pest project

## Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 2. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
  - @mpoelchau needs to do this on stage and prod prior to regular setup: https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#i5k-workspace-genome-update-sops-after-deprecation
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
  - need to modify rather than create organism page - documentation needed from @mpoelchau 
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
  - organism creation step can be skipped
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Functional annotation (@amcooksey)
- [x] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
@amcooksey it's okay to get going on the scinet/ceres portion of this whenever.

**Comment by mpoelchau** [comment]
@childers can you help us out here by
- removing the manual annotations from Apollo _stage_
- removing the organism from Apollo _stage_

Then @amcooksey can you proceed with the above steps, _except_
- adding Apollo to production
- final test list

I can work on the rest when I get back in August.

**Comment by childers** [comment]
@mpoelchau  Thanks for tagging me.

- [ ] Remove Annotations from Neolec
- [ ] Remove organism Neolec

**Comment by childers** [comment]
Had to repeat the steps due to server migration:
``` groovy ./delete_annotations_from_organism.groovy  -organismname  Neodiprion_lecontei -destinationurl https://apollo2-stage-node1-cbo.nal.usda.gov/apollo
Enter admin username: web_apollo_admin
Enter admin password: 
```
Removed organism through the admin interface

**Comment by mpoelchau** [comment]
Thanks @childers! @amcooksey how are things moving along with the remaining tasks?

**Comment by amcooksey** [comment]
@mpoelchau I had trouble logging in--got the new location from Chris. Ended up being out half of last week, just now getting back to it but having some success.

**Comment by amcooksey** [comment]
organism page: updated assembly stats. added BioProject and AgPest100 publication but did NOT remove previous BioProject and publication.

**Comment by amcooksey** [comment]
updated organism page, created new assembly, annotation, functional annotation pages. blast and hmmer don't look right on i5k-stage--see comment above.
