### ISSUE TITLE
New organism: Schistocerca cancellata

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#199]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_023864275.1
- publication associated with assembly: none
- due date: 9/19
- community contact: Hojun Song 
Childers, Anna - ARS 
Olga Dudchenko

**Special considerations:**
- This is a BPRI organism - need to link to 
  - https://dnazoo.org/assemblies/Schistocerca_cancellata
  - https://behavioralplasticity.org
- The BPRI group is working on generating RNA-Seq (our pipeline breaks due to large genome assembly size)
- This assembly is too large to add to the genomics-workspace app. Only include the transcripts and proteins. 

# Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages). 
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
  - **Note**: This assembly is too large to add to the genomics-workspace app. Only include the transcripts and proteins.  
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Functional annotation (@amcooksey)
- [x] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [x] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
@mpoelchau I get a 404 error when I go to the DNAzoo link. If I just go to DNAzoo.org and search I can't find any Schistocerca species either.

**Comment by mpoelchau** [comment]
Yep, the DNAzoo links will be live on 7/25.

**Comment by mpoelchau** [comment]
I'm working on getting permission/copyright info for the image from the journal it was published in.

**Comment by amcooksey** [comment]
Added organism page, unpublished. Still need permissions so there is no image.

**Comment by mpoelchau** [comment]
@childers @amcooksey the RefSeq annotations are available now. @amcooksey please handle the functional annotations. @childers when Amanda is done it would be great if you could do everything else. There are the following exceptions to the regular workflow due to the genome size:

- don't run RNA-Seq pipeline
- For BLAST, don't add the genome assembly

**Comment by amcooksey** [comment]
@childers fucntional annotations are done.
CERES: /project/nal_genomics/amanda.cooksey/protein_sets/Schistocerca_cancellata/NCBI Annotation Release 100 functional annotation

**Comment by mpoelchau** [comment]
@childers I reviewed this, can you update the following: 

- I don't see this org on prod Apollo
- update description in Tripal organism page (remove 'we'll add other stuff soon' segment)
- Tripal genome assembly page is missing
- add to web apollo registration config 
- add to available genome browsers page
- update scaffold and annotation readmes  in data downloads - they always require a bit of modification
- blast - for the locusts, we had decided to use the fasta files with the XM-based identifiers  (e.g. https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/023/864/275/GCF_023864275.1_iqSchCanc2.1/GCF_023864275.1_iqSchCanc2.1_protein.faa.gz, https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/023/864/275/GCF_023864275.1_iqSchCanc2.1/GCF_023864275.1_iqSchCanc2.1_rna.fna.gz) in the event that you and Trent manage to update the GW code to allow linkouts for transcripts and proteins 
- add to hmmer (with the appropriate fasta files)

**Comment by childers** [comment]
- [ ] I don't see this org on prod Apollo
- [ ] update description in Tripal organism page (remove 'we'll add other stuff soon' segment)
- [ ] Tripal genome assembly page is missing
- [ ] add to web apollo registration config
- [ ] add to available genome browsers page
- [ ] update scaffold and annotation readmes in data downloads - they always require a bit of modification
- [ ] blast - for the locusts, we had decided to use the fasta files with the XM-based identifiers (e.g. https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/023/864/275/GCF_023864275.1_iqSchCanc2.1/GCF_023864275.1_iqSchCanc2.1_protein.faa.gz, https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/023/864/275/GCF_023864275.1_iqSchCanc2.1/GCF_023864275.1_iqSchCanc2.1_rna.fna.gz) in the event that you and Trent manage to update the GW code to allow linkouts for transcripts and proteins
- [ ] add to hmmer (with the appropriate fasta files)
