### ISSUE TITLE
New organism: Schistocerca gregaria

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#200]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number:  GCF_023897955.1
- publication associated with assembly: none
- due date: Organism pages: 9/19
- community contact: Childers, Anna - ARS 

**Special considerations:**
- This is a BPRI AND Ag100Pest organism - need to link to 
  - https://dnazoo.org/assemblies/Schistocerca_gregaria
  - https://behavioralplasticity.org
  - Ag100pest as described in the org onboarding instructions
- The BPRI group is working on generating RNA-Seq (our pipeline breaks due to large genome assembly size)
- This assembly is too large to add to the genomics-workspace app. Only include the transcripts and proteins. 

# Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
  - don't add genome assembly
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Functional annotation (@amcooksey)
- [x] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
Added organism page, unpublished. Could not add image. I always get this error when I try to upload: "AJAX HTTP request terminated abnormally"
Image is only 1.1 MB

**Comment by mpoelchau** [comment]
I'm not sure why we got that error. I saved the nymphs picture as a png file and downsized it. The loader accepted it.

**Comment by mpoelchau** [comment]
@amcooksey can you add a citation for the wikipedia blurb in the description field?

**Comment by amcooksey** [comment]
added source URL for description

**Comment by mpoelchau** [comment]
@childers @amcooksey the RefSeq annotations are available now. @amcooksey please handle the functional annotations. @childers when Amanda is done it would be great if you could do everything else. There are the  following exceptions to the regular workflow due to the genome size:

- don't run RNA-Seq pipeline
- For BLAST, don't add the genome assembly

**Comment by amcooksey** [comment]
@childers functional annotations are here: /project/nal_genomics/amanda.cooksey/protein_sets/Schistocerca_gregaria/NCBI Annotation Release 100 functional annotation

**Comment by mpoelchau** [comment]
Thanks @amcooksey! Apologies, I'm going to assign the whole ticket to you instead of @childers since this one needs to be moved forward faster and chris' schedule is busy the next couple of days. The dataset will likely be featured on the main NAL website soon so it would be good to get all the resources up asap. (acknowledging limitations due to the cloud transition).

**Comment by amcooksey** [comment]
@mpoelchau I added the Tripal analysis pages (unpublished) and added N50 and GC content to organism page.
I ran BLAST and HMMER on stage (BLAST doesn't show up) and prod (looks ok to me).
I updated the permissions. (BLAT directory doesn't exist on i5k (stage or prod).

**Comment by mpoelchau** [comment]
Thanks @amcooksey. I am updating the organism page description to change the earlier placeholder text, and will publish the analysis pages. I'll update the source link on the annotations page. Everything else looks good!

**Comment by mpoelchau** [comment]
I wrote too soon @amcooksey - the functional annotations directory is missing on i5k prod (haven't checked other servers). Is this a problem with the script that moves the files, or was the directory not there to begin with?

**Comment by amcooksey** [comment]
@mpoelchau I'm inclined to say that it is a problem with the script that moves the files...but I can't get into any of the servers right now to look for anything. For some reason, my password no longer works.

**Comment by amcooksey** [comment]
I transferred the functional annotations to i5k-stage and made the symlinks. They still will need to be sync'd to prod.

**Comment by amcooksey** [comment]
Added functional annotation to production.

**Comment by mpoelchau** [comment]
@amcooksey can you do the following to finish this org up:

- add jbrowse link in available genome browsers page (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#other-tripal-changes)

Otherwise this looks good, thanks!

**Comment by amcooksey** [comment]
@mpoelchau added jbrowse link in available genome browsers page

**Comment by mpoelchau** [comment]
Thanks @amcooksey!
