### ISSUE TITLE
New organism: Schistocerca nitens

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#201]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_023898315.1
- publication associated with assembly: none
- due date: September 19th
- community contact: Hojun Song 
Childers, Anna - ARS 
Olga Dudchenko 

**Special considerations:**
- This is a BPRI organism - need to link to 
  - https://dnazoo.org/assemblies/Schistocerca_nitens
  - https://behavioralplasticity.org
- The BPRI group is working on generating RNA-Seq (our pipeline breaks due to large genome assembly size)
- This assembly is too large to add to the genomics-workspace app. Only include the transcripts and proteins. 

# Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
  - don't add the genome assembly 
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Functional annotation (@amcooksey)
- [ ] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
Added organism page, unpublished.

**Comment by mpoelchau** [comment]
@amcooksey the RefSeq annotations are available now. We can start moving along with the usual workflow, with the following exceptions due to the genome size:

- don't run RNA-Seq pipeline
- For BLAST, don't add the genome assembly

**Comment by amcooksey** [comment]
fucntional annotations: /project/nal_genomics/amanda.cooksey/protein_sets/Schistocerca_nitens/NCBI Annotation Release 100 functional annotation

**Comment by mpoelchau** [comment]
@amcooksey can you do the following to finish this org up:
- add jbrowse link in available genome browsers page (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#other-tripal-changes)
- I got a 404 not found error for the functional annotations in the data downloads


I will do these tasks:
- update description in org page
- update apollo registration settings
- clear drupal cache
- in data downloads, current genome assembly has backslashes - I'll remove them

**Comment by amcooksey** [comment]
@mpoelchau added jbrowse link in available genome browsers page

**Comment by mpoelchau** [comment]
thanks @amcooksey!
