### ISSUE TITLE
New organism: Schistocerca serialis cubense

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#202]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_023864345.2
- publication associated with assembly: none
- due date: September 19th
- community contact: Hojun Song 
Childers, Anna - ARS 
Olga Dudchenko 

**Special considerations:**
- This is a BPRI organism - need to link to 
  - https://dnazoo.org/assemblies/Schistocerca_serialis_cubense (I think - links aren't live yet...)
  - https://behavioralplasticity.org
- The BPRI group is working on generating RNA-Seq (our pipeline breaks due to large genome assembly size)
- This assembly is too large to add to the genomics-workspace app. Only include the transcripts and proteins. 

# Tasks on Ceres:
- [x] 1. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [ ] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
  - don't add the genome assembly! 
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Functional annotation (@amcooksey)
- [x] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [x] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
Added organism page, unpublished. Could not find a description for the species anywhere.

**Comment by mpoelchau** [comment]
@amcooksey the RefSeq annotations are available now. We can start moving along with the usual workflow, with the following exceptions due to the genome size: 
- don't run RNA-Seq pipeline
- For BLAST, don't add the genome assembly

**Comment by amcooksey** [comment]
functional annotations: /project/nal_genomics/amanda.cooksey/protein_sets/Schistocerca_serialis_cubense/NCBI Annotation Release 100 functional annotation

**Comment by mpoelchau** [comment]
thanks @amcooksey! can you do 2 more things:
- permissions - we're still not done fixing the permissions setup, in the meantime we'll still need to fix the permissions manually on all the servers
- Can you update the readme in the scaffold directory? (Also, am I missing documentation on this?)

**Comment by amcooksey** [comment]
@mpoelchau 
permissions should be fixed now
readme should be complete. The docs say to correct/complete the readme file in the 'data downloads' section so it gets fixed on i5k servers but not apollo servers. This time it was right on i5k-stage but not prod. I think I must not have saved the change (??) on prod this time.
