### ISSUE TITLE
New organism: Pectinophora gossypiella (pink bollworm)

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#205]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_024362695.1 
- publication associated with assembly: unpublished
- due date: October 14
- community contact: Jeff Fabrick (USDA-ARS), Colin Brent (USDA-ARS)

# Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
Some of the RNAseq samples failed during fastq-dump and were excluded from the analysis.
Succsessful: SRR7005496, SRR7005498, SRR7005499, SRR7005500, SRR7005502, SRR7005503, SRR8755468, SRR8755469
Failed : SRR7005497, SRR8755466, SRR8755467, SRR7005501, SRR2225788, SRR2225787, SRR2225790
Error: Rejected ### (all) reads with READLEN < 1 can be found in SRR######.fastq-dump.log

**Comment by mpoelchau** [comment]
Thanks @amcooksey ! I had to do a few small fixes - added the ag100pest pub to organism page; updated the org page URL in the functional annotation readme; updated the scaffold readme; and shortened the URL linkout in the functional annotatio tripal page because of a character length bug. Otherwise great though.

**Comment by mpoelchau** [comment]
@amcooksey the pub for this just came up - can you add it?

https://www.researchgate.net/profile/Amanda-Stahlke/publication/368542204_Chromosome-scale_genome_assembly_of_the_pink_bollworm_Pectinophora_gossypiella_a_global_pest_of_cotton/links/64186c5ba1b72772e412976d/Chromosome-scale-genome-assembly-of-the-pink-bollworm-Pectinophora-gossypiella-a-global-pest-of-cotton.pdf
