### ISSUE TITLE
Genome assembly update: Aethina tumida (small hive beetle)

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#206]
# OGS remapping (@mpoelchau)

- [ ] request whole-genome alignment
- [ ] Set up data directories and get data
- [x] run remap-gff3

# Change old content (@mpoelchau)
- [ ] back up and deprecate old Apollo2
- [ ] back up and deprecate old fasta files in BLAST 
- [ ] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_024364675.1 
- publication associated with assembly: unpublished
- due date: October 28
- community contact: Jay Evans (USDA-ARS)

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
@amcooksey can you do the functional annotations, and @childers do everything else for 'Tasks on Ceres' and 'Tasks on NAL servers'?

You can start working on the tasks on Ceres now, but I'll need to clean up on the servers first before you can start on the tasks on the NAL servers.

**Comment by amcooksey** [comment]
@childers Functional annotations are here:
/project/nal_genomics/amanda.cooksey/protein_sets/Aethina_tumida/NCBI Annotation Release 101 functional annotation

**Comment by mpoelchau** [comment]
cp /app/data/other_species/aettum/icAetTumi1.1/scaffold/GCF_024364675.1_icAetTumi1.1_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/aettum/icAetTumi1.1/scaffold/analyses/NCBI\ Aethina\ tumida\ Annotation\ Release\ 101/GCF_024364675.1_icAetTumi1.1_cds_from_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/aettum/icAetTumi1.1/scaffold/analyses/NCBI\ Aethina\ tumida\ Annotation\ Release\ 101/GCF_024364675.1_icAetTumi1.1_rna_from_genomic.fna /usr/local/i5k/media/blast/db/
cp /app/data/other_species/aettum/icAetTumi1.1/scaffold/analyses/NCBI\ Aethina\ tumida\ Annotation\ Release\ 101/GCF_024364675.1_icAetTumi1.1_translated_cds.faa /usr/local/i5k/media/blast/db/

python manage.py addorganism Aethina tumida

python manage.py addblast Aethina tumida -t nucleotide Genome Assembly -f GCF_024364675.1_icAetTumi1.1_genomic.fna -d 'Aethina tumida genome assembly, icAetTumi1.1'
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_genomic.fna -m
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_genomic.fna -p
python manage.py blast_shown GCF_024364675.1_icAetTumi1.1_genomic.fna --shown true
python manage.py addjbrowse GCF_024364675.1_icAetTumi1.1_genomic.fna https://apollo.nal.usda.gov/apollo/Aethina_tumida/jbrowse/

python manage.py addblast Aethina tumida -t nucleotide Transcript -f GCF_024364675.1_icAetTumi1.1_rna_from_genomic.fna -d 'Aethina tumida NCBI Annotation release 101, transcripts'
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_rna_from_genomic.fna -m
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_rna_from_genomic.fna -p
python manage.py blast_shown GCF_024364675.1_icAetTumi1.1_rna_from_genomic.fna --shown true

python manage.py addblast Aethina tumida -t peptide Protein -f GCF_024364675.1_icAetTumi1.1_translated_cds.faa -d 'Aethina tumida NCBI Annotation release 101, translated CDS'
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_translated_cds.faa -m
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_translated_cds.faa -p
python manage.py blast_shown GCF_024364675.1_icAetTumi1.1_translated_cds.faa --shown true

python manage.py addblast Aethina tumida -t nucleotide Transcript -f GCF_024364675.1_icAetTumi1.1_cds_from_genomic.fna -d Aethina tumida NCBI Annotation release 101, CDS
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_cds_from_genomic.fna -m
python manage.py blast_utility GCF_024364675.1_icAetTumi1.1_cds_from_genomic.fna -p
python manage.py blast_shown GCF_024364675.1_icAetTumi1.1_cds_from_genomic.fna --shown true

python manage.py addhmmer Aethina tumida -f /usr/local/i5k/media/blast/db/GCF_024364675.1_icAetTumi1.1_translated_cds.faa -d 'Aethina tumida NCBI Annotation release 101, translated CDS'

**Comment by mpoelchau** [comment]
Moved old Apollo/blast resources temporarily to training while working out manual annotation decisions.
