### ISSUE TITLE
Genome assembly update: Bombus impatiens

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#208]
# Change old content - @mpoelchau 
- [x] back up and deprecate old Apollo2
- [x] back up and deprecate old fasta files in BLAST 
- [x] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_000188095.3
- publication associated with assembly: doi:10.1186/s13059-015-0623-3 
- due date: 10/10/2022
- community contact: Chris Elsik, University of Missouri

## Tasks on Ceres: @amcooksey 
- Functional annotation not needed, already completed
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  @amcooksey (after @mpoelchau has cleaned up)
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
@amcooksey okay to move forward on Ceres for now. We will also need to add an additional OGS track while the files are still on Ceres. Lmk when you are done on Ceres and I can add it

**Comment by amcooksey** [comment]
@mpoelchau Ceres steps are done. You can add OGS track whenever you are ready.
/project/nal_genomics/organism_onboarding/bomimp

**Comment by mpoelchau** [comment]
@amcooksey I've added the OGS to Ceres and removed the organism in the Apollo app on stage. things should be good to go on staging, lmk when you're ready to move to prod

**Comment by amcooksey** [comment]
@mpoelchau Everything looks ok on stage to me.

**Comment by amcooksey** [comment]
@mpoelchau I think this is updated and ready for review. The only thing I know needs to be fixed is the date on the Tripal assembly page needs to 2011, not 2012.
