### ISSUE TITLE
New organism: Bombus affinis

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#212]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_024516045.1
- publication associated with assembly: none
- due date: 11/25 (or after TG)
- community contact: Jonathan Koch, USDA

# Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

# Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
@amcooksey thanks, a couple of additions:
- apollo/jbrowse - was there any RNA-Seq?
- I forgot to specify that this is an Ag100Pest and Beenome 100 project. Can you add the usual Ag100Pest info, and then add in the organism description field "This genome project is part of the Ag100Pest ([http://i5k.github.io/ag100pest](http://i5k.github.io/ag100pest)) and Beenome 100 projects."
- in the organism description, can you remove the links (e.g. [4] ), since they don't link to anything anymore?
- readme files - the line 'information about this dataset can be found...' should link to the Tripal organism page
- scaffold readme file - you can typically remove the 'postprocessing' line

**Comment by amcooksey** [comment]
@mpoelchau There was no RNAseq. I have made the other edits.

**Comment by mpoelchau** [comment]
@amcooksey can you try to run the RNA-Seq pipeline against the genome with Bombus terrestris RNA-Seq? I think all you'd need to do at first is change the taxid to  Bombus terrestris. We'll probably have to manually change the track names after that.

**Comment by amcooksey** [comment]
@mpoelchau I have successfully tricked Apollo into displaying all of the Bomter RNAseq tracks.

**Comment by mpoelchau** [comment]
Thanks @amcooksey !

**Comment by amcooksey** [comment]
publication added and referenced in assembly page. organism page will need to be updated when we can make edits.
