### ISSUE TITLE
Genome assembly update: Zeugodacus cucurbitae

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#235]
# Change old content @mpoelchau 
- [x] back up and deprecate old Apollo2
- [x] back up and deprecate old fasta files in BLAST 
- [x] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications @amcooksey 
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number:GCF_000806345.1
- publication associated with assembly: no
- due date: 6/16
- community contact: Sheina Sim, USDA and Scott Geib, USDA

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
@mpoelchau I think everything is under Zeugodacus now and there aren't any more references to Bactrocera cucurbitae.

**Comment by amcooksey** [comment]
This looks like it's already up-to-date.

**Comment by amcooksey** [comment]
previous versions were not 'zeugodacus' but bactrocera. I don't remember how exactly we changed it but there may still be some reference to bactrocera somewhere.

**Comment by amcooksey** [comment]
I added the Ag100Pest publication to the assembly page. It save the change but I got this message:
The URL alias, Genomeassembly/836645, already exists for multiple pages! Please ensure the pattern supplied on the [Genome Assembly Edit Page](https://i5k.nal.usda.gov/admin/structure/bio_data/manage/bio_data_13) under URL Path options is unique.

**Comment by amcooksey** [comment]
I haven't found any reason that the new Zeugodacus versions don't show up in a search.
All the names have the Zeugodacus genus and they are link to the same organism as the older versions (which show up in a search).

**Comment by mpoelchau** [comment]
Search issue seems to have resolved itself now.
