### ISSUE TITLE
Genome assembly update: Hyalella azteca

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#242]
# OGS remapping (@mpoelchau)
- remap OGS
- remap manual annotations

# Change old content
- [ ] back up and deprecate old Apollo2
- [ ] back up and deprecate old fasta files in BLAST 
- [ ] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_000764305.2
- publication associated with assembly: https://doi.org/10.1021/acs.est.8b00837
- due date: 9/5/2023
- community contact: Helen Poynton

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
@amcooksey I may need to add a track or 2 before you move from stage to prod.

**Comment by mpoelchau** [comment]
path to lifted over manual annotations on ceres (ready to load into UcA on stage): `/project/nal_genomics/monica.poelchau/species_files/hyaazt/GCA_000764305.3/scaffold/analyses/manual-annotations/hyaazt-apollo-annotations-lifted.gff3_phase`

**Comment by amcooksey** [comment]
I think everything is done.

**Comment by mpoelchau** [comment]
@amcooksey thanks! can you
- add the OGS v1.3 to the data downloads - put this in the official/primary gene set folder and move the NCBI annotations to 3. additional gene sets. Files are in the analyses folder
- add OGSv 1.3 to blast/hmmer and remove OGSv1.2
