### ISSUE TITLE
Genome assembly update: Orussus abietinus

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#252]
# remapping
- manual annotations
- OGS

# Change old content
- [ ] back up and deprecate old Apollo2
- [ ] back up and deprecate old fasta files in BLAST 
- [ ] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_000612105.2
- publication associated with assembly:https://i5k.nal.usda.gov/bio_data/836861, https://i5k.nal.usda.gov/bio_data/836870
- due date:
- community contact: i5k Workspace@NAL

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
FYI, we seem to have run some update workflows a few years ago, but those never made it to production...
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [ ] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
updated apollo except for manual annotations. the files are here: /app/data/other_species/oruabi/Oabi_2.0/scaffold/analyses/manual_curation/ 
and here: /app/data/amanda.cooksey/apollo-arrow/oruabi/

**Comment by amcooksey** [comment]
All the Tripal pages were already up-to-date except I added a functional annotation page for NCBI 101

**Comment by mpoelchau** [comment]
@amcooksey thanks! Could you also:
- create a tripal analysis page for OGS v1.0 - I didn't realize we didn't have one. I can help with the metadata
- add genome update info to the organism description

Again, will leave open until we have the manual annotation load issue resolved.

I changed the community contact to the i5k workspace per communication with Jan 4/7/2023

**Comment by amcooksey** [comment]
updated organism description

**Comment by amcooksey** [comment]
added Tripal page to OGS v1.0

**Comment by amcooksey** [comment]
added manual annotations and metadata. update should be complete now.
