### ISSUE TITLE
Genome assembly update:  Amyelois transitella

### ISSUE THREAD

**Issue by amcooksey** [NAL-i5K/general_issues#258]
# Change old content
- [ ] back up and deprecate old Apollo2
- [ ] back up and deprecate old fasta files in BLAST 
- [ ] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_032362555.1
- publication associated with assembly: TBD
- due date: Dec 20
- community contact: Raman Bansal

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [ ] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [x] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
@amcooksey how are things going with this ticket? FYI it's an Ag100Pest update with a bunch of manual annotations...

**Comment by amcooksey** [comment]
looks like this one got lost in the shuffle.  i will start the update this week.

**Comment by amcooksey** [comment]
updated apollo except for the manual annotations. liftoff has been run. the files are here:
/app/data/other_species/amytra/ilAmyTran1.1/scaffold/analyses/manual-curation
AND 
/project/nal_genomics/amanda.cooksey/manual_annotations_and_OGS/amytra/ilAmyTran1.1/scaffold/analyses/manual-curation

**Comment by amcooksey** [comment]
update is be complete now except for the manual annotations.

**Comment by mpoelchau** [comment]
@amcooksey the genome assembly page is actually a genome annotation page. This is why this assembly didn't show up in the genome list. I'm not sure there's a way to change the category - you may just have to create a new page and delete the old one.  https://i5k.nal.usda.gov/bio_data/1394540

**Comment by amcooksey** [comment]
Made a new genome assembly page for Amyelois transitella genome assembly ilAmyTran1.1 (GCF_032362555.1) and deleted the old one.

**Comment by amcooksey** [comment]
manual annotations and metadata added. phase needs to be reconciled to the original liftoff phase for these two transcripts:
a30c3305-214a-4d24-a7e8-3f1abd3a089a
1fbc0006-5e31-4222-96cc-cc1ad13a75be
