### ISSUE TITLE
Genome assembly update: Tigriopus californicus

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#265]
# OGS remapping

- remap TCalif_v1.0. Let's retire all of the supplemental evidence tracks, though.
- remap manual annotations

# Change old content
- [x] back up and deprecate old Apollo2
- [x] back up and deprecate old fasta files in BLAST 
- [x] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_007210705.1
- publication associated with assembly: Genomic signatures of mitonuclear coevolution across populations of Tigriopus californicus. https://pubmed.ncbi.nlm.nih.gov/29988158/
- due date: 3/24
- community contact: Felipe Barreto

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)
- [x] We should look into regenerating the mapped DNA-Seq that's currently on the browsers

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Add is_obsolete property to OLD genome assembly Tripal pages. See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#tripal-1 
- [x] 5. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 6. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
There are also population resequencing tracks for this one that we'll need to recreate.

**Comment by amcooksey** [comment]
I can't find any DNAseq samples in the SRA that appear to match those in Apollo. There are San Diego (SRR10760094) and Bodega (SRR10760095) populations but they belong to LSU and none of the other populations are represented.

**Comment by mpoelchau** [comment]
I checked the data availability statement in their publication, and they reference  SRX2746698–SRX2746704 for the population data. Do those accessions make sense?

**Comment by amcooksey** [comment]
I think that's them. They named all the sequecing as if it's pooled rather than separate populations but if you dig down to the underlying BioSample metadata they are separate.

**Comment by amcooksey** [comment]
added DNAseq info to trackList.json like this:

echo '{
"urlTemplate" : "analyses/Tigriopus_californicus_Variant_2024-04-01_v1.0/Abalone_Cove_filtered.vcf.gz",
"type" : "HTMLVariants",
"category" : "Variants",
"storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
"key" : "T._californicus_Abalone_Cove_variants",
"label" : "T._californicus_Abalone_Cove_variants"
         "metadata" : {
            "Analysis provider" : "i5k Workspace@NAL",
            "Data source" : "<a href='https://www.ncbi.nlm.nih.gov/sra/?term=SRR5458691'>SRR5458691 </a>,<a href='https://www.ncbi.nlm.nih.gov/sra/?ter>,
            "Analysis method" : "https://github.com/NAL-i5K/SRAtoVCF",
            "Publication status" : "Analysis: NA; Source data: see individual SRA accessions",
            "Track legend" : "Visualization of population variants generated by GATK 4.4.0."
         }
}' > Abalone_Cove.json

singularity exec -B /project/nal_genomics/organism_onboarding/tigcal/output/other_species/tigcal/Tcal_SD_v2.1/jbrowse/data/:/jbrowse/data \
/project/nal_genomics/shared_programs/jbrowse_1.16.11--pl5321h9f5acd7_5.sif /usr/local/opt/jbrowse/bin/add-track-json.pl \
Abalone_Cove/Abalone_Cove.json /jbrowse/data/trackList.json

**Comment by amcooksey** [comment]
update complete
