### ISSUE TITLE
Genome assembly update: Catajapyx aquilonaris

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#266]
# OGS remapping

- remap Baylor annotations. Let's deprecate all the supplementary evidence though, and the 1kite transcriptome.
- remap manual annotations

# Change old content
- [ ] back up and deprecate old Apollo2
- [ ] back up and deprecate old fasta files in BLAST 
- [ ] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCA_000934665.2
- publication associated with assembly: Gene content evolution in the arthropods
- due date: 3/25
- community contact: TBD

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Add is_obsolete property to OLD genome assembly Tripal pages. See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#tripal-1 
- [x] 5. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 6. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
Thanks @amcooksey ! I did a few tweaks:

- updated data downloads link 
- updated readme contact
- update community contact (removed email and added institution_
- added info on liftover to Jbrowse metadata 
- changed category in apollo
