### ISSUE TITLE
Genome assembly update: Heliothis virescens

### ISSUE THREAD

**Issue by amcooksey** [NAL-i5K/general_issues#271]
# OGS remapping

- [ ] request whole-genome alignment
- [ ] Set up data directories and get data
- [ ] run remap-gff3

# manual annotation remapping

- [ ] request whole-genome alignment
- [ ] Set up data directories and get data
- [ ] run remap-gff3

# Change old content
- [ ] back up and deprecate old Apollo2
- [ ] back up and deprecate old fasta files in BLAST 
- [ ] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCA_002382865.2
- publication associated with assembly: TBD
- due date: 3/27
- community contact: Megan Fritz, mfritz13@umd.edu

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Add is_obsolete property to OLD genome assembly Tripal pages. See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#tripal-1 
- [x] 5. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 6. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by mpoelchau** [comment]
Let's put this one at the back of the queue - I should check in with Megan on her group's annotation status first.

**Comment by amcooksey** [comment]
OGS, manual annotations and RNAseq all loaded into apollo. waiting for space on i5k to finish the update.

**Comment by amcooksey** [comment]
I think this is completely updated now. I was only able to obsolete the old assembly on production. The stage admin menu doesn't have all of the same options as production.

**Comment by MonicaPoelchau-USDA** [comment]
@amcooksey What was missing on stage?

**Comment by amcooksey** [comment]
production:
![image](https://github.com/user-attachments/assets/050cdbda-990c-4507-9ade-9dac7c08302d)

stage:
![image](https://github.com/user-attachments/assets/fd7a4e05-7de2-4883-a4c1-28c2bc9f4fb6)

**Comment by MonicaPoelchau-USDA** [comment]
- Looks like there's a publication associated with the genome assembly - can you add this? https://doi.org/10.1016/j.ygeno.2022.110441
- I changed the method from liftover to LiftOff in the OGS tripal page
- Can you add text about the update in the organism page description? 
- Were there unmapped features? If so, we should include the unmapped_features.txt file in the data downloads. Otherwise we need to state in the readme that all features mapped. 
- I will update the OGS description
- I will set up the OGS Ag Data Commons submission

**Comment by amcooksey** [comment]
I added publication, updated the org page description and added the unmapped_features.txt file
