### ISSUE TITLE
Genome assembly update: Mamestra configurata

### ISSUE THREAD

**Issue by amcooksey** [NAL-i5K/general_issues#272]
# Change old content
- [ ] back up and deprecate old Apollo2
- [ ] back up and deprecate old fasta files in BLAST 
- [ ] back up and deprecate old fasta files in Hmmer 

# Add new content to i5k Workspace applications
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCA_002192655.3
- publication associated with assembly: TBD
- due date: 3/27
- community contact: Cathy Coutu, Cathy.Coutu@AGR.GC.CA

## Tasks on Ceres:
- [x] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [x] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [x] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

## Tasks on the NAL servers:  
- [x] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [x] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [x] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [x] 4. Add is_obsolete property to OLD genome assembly Tripal pages. See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#tripal-1 
- [x] 5. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [x] 6. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 7. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 8. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
This is genbank not refseq. It doesn't have an official annotation with a version but it has all the files (CDS, transcripts etc). There is minimal functional annotation. There is almost nothing in the gff so it doesn't look very nice on the browser. I also didn't make an annotation or functional annotation tripal page (since there is "no annotation").
Otherwise, it's complete.

**Comment by mpoelchau** [comment]
Looks like the mitochondrion is annotated but nothing else. I will update the track description and other metadata in jbrowse, and the description of the Blast database. Perhaps the organism page description also.

**Comment by amcooksey** [comment]
RNAseq tracks to be added:
Midgut illumina (after removal of MacoNPV reads): SRR3114051, SRR3114052, SRR3114053, SRR3114069, SRR3114070, SRR3114071, SRR25755032, SRR25755033, SRR25755037, SRR25755042*
Midgut 454: SRR29198352
Carcass 454: SRR29198353 and SRR29198354
Head illumina: SRR17048747, SRR17048749, SRR17048751, SRR17048753, SRR17048755, SRR17048757
Antennae illumina: SRR17048746, SRR17048748, SRR17048750, SRR17048752, SRR17048754, SRR17048756

**Comment by amcooksey** [comment]
added RNAseq tracks
