### ISSUE TITLE
New organism:  Anabrus simplex

### ISSUE THREAD

**Issue by amcooksey** [NAL-i5K/general_issues#286]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update for full description of each task (requires gitlab login)

- assembly accession number: GCF_040417275.1
- publication associated with assembly: TBD
- due date: 9/10/24
- community contact: TBD

# Tasks on Ceres:
- [ ] 1. Create functional annotations (@amcooksey). https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#0-run-the-functional-annotation-pipeline
- [ ] 2. Run the final_workflow.cwl component of the organism_onboarding pipeline (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#1-run-the-final_workflowcwl-component-of-the-organism_onboarding-pipeline-httpsgithubcomnal-i5korganism_onboarding)
- [ ] 3. Run RNA-Seq pipeline, steps 1 and 2 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-RNA-Seq-data-to-an-i5k-Workspace-project-with-the-NAL_RNA_seq_annotation_pipeline)

# Tasks on the NAL servers:  
- [ ] 1. Move the final_workflow.cwl output from SCINet to apollo2-stage-node1 (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#3-move-the-final_workflowcwl-output-from-scinet-to-apollo2-stage-node1)
- [ ] 2. Apollo setup on the apollo2-stage-node1 and apollo2-node1 servers (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#4-apollo-setup-on-the-apollo2-stage-node1-and-apollo2-node1-servers) 
- [ ] 3. Set up Tripal pages (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#6-set-up-tripal-pages)
- [ ] 4. Set up BLAST and HMMER (genomics-workspace) (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#7-set-up-blast-and-hmmer-genomics-workspace)
- [ ] 5. Set up data downloads (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#8-set-up-data-downloads)
- [ ] 6. Final Test List (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-final-test-list)
- [ ] 7. Advertising (https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#10-advertising) (@mpoelchau)

**Comment by amcooksey** [comment]
load onto apollo (stage and prod). waiting for space on i5k servers to finish.

**Comment by amcooksey** [comment]
GCF_040417275.1 was suppressed: use GCF_040414725.1 instead

**Comment by amcooksey** [comment]
removed GCF_040417275.1 from apollo stage and prod

**Comment by amcooksey** [comment]
loaded the correct version into apollo stage and prod. waiting for space on i5k servers to finish.

**Comment by amcooksey** [comment]
data downloads complete on stage. 
blast looks complete on stage but the genome isn't showing up in the list even though django says it should. I will wait to see if it appears. This species is kind of big and has been slow at every step.

**Comment by amcooksey** [comment]
finally added. everything is done except the genome blast. the genome is quite large but we should be able to add it to blast once we update to the newer blast version.

**Comment by mpoelchau** [comment]
thanks! I added the organism to the Apollo registration and the available genome browsers page, and published the tripal pages. Could you update the scaffold readme:
https://i5k.nal.usda.gov/sites/default/files/data/Arthropoda/anasim-%28Anabrus_simplex%29/Current%20Genome%20Assembly/1.Genome%20Assembly/ASM4041472v1/Scaffolds/readme.txt

I think after that I can advertise.

**Comment by amcooksey** [comment]
I updated the scaffold readme.

**Comment by mpoelchau** [comment]
Two more things:

- please add Maeva Techer and Jackson Linde as community contacts (from TAMU)
- could you add the following publication and associate it with the organism? 

Hoang, T.; Foquet, B.; Rana, S.; Little, D.W.;Woller, D.A.; Sword, G.A.; Song, H. Development of RNAi Methods for the Mormon Cricket, Anabrus simplex (Orthoptera: Tettigoniidae). Insects 2022, 13, 739. https://doi.org/10.3390/insects13080739

**Comment by amcooksey** [comment]
added contacts and publication
